### PR TITLE
Refactor examples/bouncing_balls.py

### PR DESCRIPTION
**Pull request by zman97211**
I re-wrote this to simply better understand how the example was working. I notice there doesn't seem to be much commonality between the various examples (beyond my cursory look).

Anyway, this should be more understandable than it was before.

### CODE REVIEW

**Comment by viblo** [comment]
Thanks for the PR! I will take a closer look and try it out as soon as I have the chance

**Comment by viblo** [comment]
There are two reasons why most examples look different. Partly is because they were written in different times, and the older ones have mostly only received enough updates to run, but not for a consistent style. But its also to show different ways to do things (However this is a smaller reason and for it to work well there should be some indication as to what ways are good ways and what are just old code).

Anyway, to your PR:
Overall it looks good, nice work. To comments:
- It seems like it doesn't run on python 2.7. Unless necessary all pymunk code should work in both 2.7 and 3.x. 
- Even thou its not strictly required since the pygame util module will also import pymunk I think its good to explicitly import pymunk. That the util module does this is more of a side effect than on purpose, so best to not rely on that.

**Comment by zman97211** [comment]
I'll make some changes and test with 2.7. I think there are a couple comments I could update as well.

**Comment by zman97211** [comment]
Assuming the CI checks pass, this runs for me on 2.7.15 and 3.7.0.

**Comment by viblo** [comment]
Looking good, thanks!

**Pull request merged**
