### PR TITLE
added pyboxes example - wilson koder

### PR DESCRIPTION
**Pull request by WilsonKoder**
tutorial here: http://wilsonkoder.com/pymunkTutorial.html

### CODE REVIEW

**Comment by viblo** [comment]
I got
Please choose a new color (green, red, blue, yellow): yellow
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    execfile(name)
  File "pyboxes_advanced.py", line 99, in <module>
    if newColor.lower() == "green":
AttributeError: 'tuple' object has no attribute 'lower'

**Comment by WilsonKoder** [comment]
Let me check that today.

**Comment by viblo** [comment]
(I only had time to test the code today, but havent looked at it carefully yet)
Another thing I noticed is that it doesnt run on python 3. 

My thinking is that either put the files in a contrib folder inside examples and then maybe it could be ok without python 3 support, or put it directly into the other examples, but then it has to run on python 3. But then there are also other considerations, I would like all examples to follow the same style if possible and be structured in a similar way. I know its not perfectly right now, but its my goal at least. However, that is of course harder for outside contributions.. (but no concern if they are separated in their own folder)

**Comment by viblo** [comment]
Seems like the website doesnt work anymore, and the code is outdated, so Ill close this PR. Feel free to open a new one if updated.

**Pull request closed without merging**
