### PR TITLE
Thread Safety

### PR DESCRIPTION
**Pull request by Berserker66**
In a multi-threaded environment, multiple shapes can end up with the same ID, tripping assertion errors.
This fixes that part. Didn't see a noticeable performance change, but mileage may vary.

### CODE REVIEW

**Comment by Berserker66** [comment]
Another thing that just happened is that adding shapes via threads can on occasion also backfire.
If the space is in-step, it adds the shapes to a set of stuff to be added later. However, if shapes get added while the back-end of the step function handles them, you get that the set changed during iteration.

Would be an easy enough fix by using the Queue module for this, which is made for this kind of purpose.

Should I keep piling thread-safety changes into this pull-request for the time being, or what's a good way of dealing with this? (Asking the pymunk authors here)
Preparing the module for threading seems like a good idea considering hastyspace may be coming.

**Comment by viblo** [comment]
First off, let me say thanks for this PR and the issues you've raised! It sounds like you are working on a very cool project.

I think we need to reflect on this a little bit. Pymunk is as you have noted not thread safe at the moment. For thread safety I think there are only two options, either go all in and make everything safe, or no need to do anything at all. As you noted in #125 the performance benefit (if any) doesnt seem to be very noticeable if I understood you correctly. Does it then make sense to add locks all over to make it safe or should the user do his/her own locking? 

Im not rejecting the idea fully, but it would be interesting to hear your thoughts about this, and how much work it would add to make locking in the client code?

(Im not sure its directly connected to making the step function threaded/hastyspace. A threaded solver gives benefit regardless if its possible to modify the space from multiple threads safely or not.)

**Comment by Berserker66** [comment]
Ok, let's think this over.

I had a look around the module and on a glance, there are not that many changes needed. Most are things that are just refactors (turn sets into to queues, for example, turn in_use into a thread lock (maybe)), but there could be stuff I'm missing on this quick look.
As for the benefit part, cffi does release the gil, so at the very least; the step could happen while you queue up objects to be removed/added. This could easily mean a ~2X speedup in threaded code. I doubt much more than that can be gained. With hastyspace you might get to 3x speedup, if you're lucky.

Another issue is that right now the module segfaults when the application exits on a multithreaded environment. I'm not 100% sure as to the reason, but my guess is that due to the old-style cffi callbacks not re-acquiring the gil, when being called back, that that happens in some part of the cleanup and something needs gil doesn't -> segfault. But that's just assumption, debugging seg faults is fun..
But one could look into this as well, while at it.

The stuff in #125 is very special - it looks almost exclusively at creating shapes, which will never multithread well because it needs the GIL (in pymunk, at least). The issue was more, that creating shapes from multiple threads was actually severely detrimental to performance, which is even worse. What I've also found when tinkering with it, is you can protect the entire shape creation by a threadlock, like the one in the this pull request and it will actually help performance (in multithreaded code), due to actually acquiring the gil when it needs to, thanks to an outer lock, instead of waiting several times for the gil to be available.

The idea with improving things for hastyspace is that certain stuff that happens during the step through callbacks would hit less GIL barriers thanks to outer threadlocks and may gain some performance benefit there. If that actually happens would remain to be seen.

Bottomline -
Regarding pymunk, it would be more "proper" to protect objects with the appropriate threading primitives. Most of them add a negligible overhead as well, so nothing is lost for single threaded applications. For properly multithreaded applications the benefit could range from not faulting/crashing to some performance benefit. I'd call the benefit an extra, not faulting should already be worth it.

For Client applications.
Depends. The "simple" solution in my case is to put all pymunk stuff into a physics thread and queue up any commands that regard physics and have the physics thread do a main loop of

```
[pseudocode]
while 1:
    dt = determine_delta_time()
    space.step(dt)
    for func, args in self.queue:
        func(*args)
    sleep_if_needed
```
Which I already put on my todo list yesterday. This will neatly prevent any faulting because as far as pymunk is concerned there is only one relevant thread.
It also means I'll likely have some kind of delayed physics_init for all my entities, which may be awkward to work with.

So, yeah - this solution would be sufficient for me, for now, but I'd prefer to be able to call from any thread - queues do add some overhead too.

**Comment by Berserker66** [comment]
So, the remote unittester seem to be getting stuck on test_common -> UnitTestBugs -> testNoStaticShape

Which is odd, since locally this happens:

```
PS E:\pymunk-multithread\tests> py -m unittest
Loading chipmunk for Windows (64bit) [C:\Program Files\Python36\lib\site-packages\pymunk\chipmunk.dll]
......................................................................................................................................................................................
----------------------------------------------------------------------
Ran 182 tests in 0.308s

OK
PS E:\pymunk-multithread\tests> py -m unittest -v
Loading chipmunk for Windows (64bit) [C:\Program Files\Python36\lib\site-packages\pymunk\chipmunk.dll]
testContactPointSet (test_arbiter.UnitTestArbiter) ... ok
testFriction (test_arbiter.UnitTestArbiter) ... ok
testImpulse (test_arbiter.UnitTestArbiter) ... ok
testIsFirstContact (test_arbiter.UnitTestArbiter) ... ok
testIsRemoval (test_arbiter.UnitTestArbiter) ... ok
testRestitution (test_arbiter.UnitTestArbiter) ... ok
testShapes (test_arbiter.UnitTestArbiter) ... ok
testSurfaceVelocity (test_arbiter.UnitTestArbiter) ... ok
testTotalKE (test_arbiter.UnitTestArbiter) ... ok
test_convex_decomposition (test_autogeometry.UnitTestAutoGeometry) ... ok
test_is_closed (test_autogeometry.UnitTestAutoGeometry) ... ok
test_march_hard (test_autogeometry.UnitTestAutoGeometry) ... ok
test_march_soft (test_autogeometry.UnitTestAutoGeometry) ... ok
test_simplify_curves (test_autogeometry.UnitTestAutoGeometry) ... ok
test_simplify_vertexes (test_autogeometry.UnitTestAutoGeometry) ... ok
test_to_convex_hull (test_autogeometry.UnitTestAutoGeometry) ... ok
test_collect_segment (test_autogeometry.UnitTestPolylineSet) ... ok
testCreation (test_bb.UnitTestBB) ... ok
testMerge (test_bb.UnitTestBB) ... ok
testMethods (test_bb.UnitTestBB) ... ok
testPickle (test_bb.UnitTestBB) ... ok
testCoordinateConversion (test_body.UnitTestBody) ... ok
testDynamic (test_body.UnitTestBody) ... ok
testEachArbiters (test_body.UnitTestBody) ... ok
testForce (test_body.UnitTestBody) ... ok
testGetConstraints (test_body.UnitTestBody) ... ok
testGetShapes (test_body.UnitTestBody) ... ok
testImpulse (test_body.UnitTestBody) ... ok
testKinematic (test_body.UnitTestBody) ... ok
testKineticEnergy (test_body.UnitTestBody) ... ok
testMassMomentFromShape (test_body.UnitTestBody) ... ok
testPickle (test_body.UnitTestBody) ... ok
testPositionFunction (test_body.UnitTestBody) ... ok
testProperties (test_body.UnitTestBody) ... ok
testRepr (test_body.UnitTestBody) ... ok
testSleep (test_body.UnitTestBody) ... ok
testSleepWithGroup (test_body.UnitTestBody) ... ok
testStatic (test_body.UnitTestBody) ... ok
testVelocityConversion (test_body.UnitTestBody) ... ok
testVelocityFunction (test_body.UnitTestBody) ... ok
testManyBoxCrash (test_common.UnitTestBugs) ... ok
testNoStaticShape (test_common.UnitTestBugs) ... ok
testAreaHelpers (test_common.UnitTestGeneral) ... ok
testGeneral (test_common.UnitTestGeneral) ... ok
testMomentHelpers (test_common.UnitTestGeneral) ... ok
testA (test_constraint.UnitTestConstraint) ... ok
testActivate (test_constraint.UnitTestConstraint) ... ok
testB (test_constraint.UnitTestConstraint) ... ok
testCollideBodies (test_constraint.UnitTestConstraint) ... ok
testErrorBias (test_constraint.UnitTestConstraint) ... ok
testImpulse (test_constraint.UnitTestConstraint) ... ok
testMaxBias (test_constraint.UnitTestConstraint) ... ok
testMaxForce (test_constraint.UnitTestConstraint) ... ok
testPickle (test_constraint.UnitTestConstraint) ... ok
testDamping (test_constraint.UnitTestDampedRotarySpring) ... ok
testPickle (test_constraint.UnitTestDampedRotarySpring) ... ok
testRestAngle (test_constraint.UnitTestDampedRotarySpring) ... ok
testStiffness (test_constraint.UnitTestDampedRotarySpring) ... ok
testAnchor (test_constraint.UnitTestDampedSpring) ... ok
testDamping (test_constraint.UnitTestDampedSpring) ... ok
testPickle (test_constraint.UnitTestDampedSpring) ... ok
testRestLength (test_constraint.UnitTestDampedSpring) ... ok
testStiffness (test_constraint.UnitTestDampedSpring) ... ok
testPhase (test_constraint.UnitTestGearJoint) ... ok
testPickle (test_constraint.UnitTestGearJoint) ... ok
testRatio (test_constraint.UnitTestGearJoint) ... ok
testAnchor (test_constraint.UnitTestGrooveJoint) ... ok
testGroove (test_constraint.UnitTestGrooveJoint) ... ok
testPickle (test_constraint.UnitTestGrooveJoint) ... ok
testAnchor (test_constraint.UnitTestPinJoint) ... ok
testDistane (test_constraint.UnitTestPinJoint) ... ok
testPickle (test_constraint.UnitTestPinJoint) ... ok
testAnchorByAnchor (test_constraint.UnitTestPivotJoint) ... ok
testAnchorByPivot (test_constraint.UnitTestPivotJoint) ... ok
testPickle (test_constraint.UnitTestPivotJoint) ... ok
testAngle (test_constraint.UnitTestRatchetJoint) ... ok
testPhase (test_constraint.UnitTestRatchetJoint) ... ok
testPickle (test_constraint.UnitTestRatchetJoint) ... ok
testRatchet (test_constraint.UnitTestRatchetJoint) ... ok
testMax (test_constraint.UnitTestRotaryLimitJoint) ... ok
testMin (test_constraint.UnitTestRotaryLimitJoint) ... ok
testPickle (test_constraint.UnitTestRotaryLimitJoint) ... ok
testPickle (test_constraint.UnitTestSimleMotor) ... ok
testSimpleMotor (test_constraint.UnitTestSimleMotor) ... ok
testAnchor (test_constraint.UnitTestSlideJoint) ... ok
testMax (test_constraint.UnitTestSlideJoint) ... ok
testMin (test_constraint.UnitTestSlideJoint) ... ok
testPickle (test_constraint.UnitTestSlideJoint) ... ok
testCircleBB (test_shape.UnitTestCircle) ... ok
testCircleNoBody (test_shape.UnitTestCircle) ... ok
testOffset (test_shape.UnitTestCircle) ... ok
testOffsetUnsafe (test_shape.UnitTestCircle) ... ok
testPickle (test_shape.UnitTestCircle) ... ok
testRadius (test_shape.UnitTestCircle) ... ok
testRadiusUnsafe (test_shape.UnitTestCircle) ... ok
testBB (test_shape.UnitTestPoly) ... ok
testCreateBox (test_shape.UnitTestPoly) ... ok
testInit (test_shape.UnitTestPoly) ... ok
testPickle (test_shape.UnitTestPoly) ... ok
testRadius (test_shape.UnitTestPoly) ... ok
testRadiusUnsafe (test_shape.UnitTestPoly) ... ok
testVertices (test_shape.UnitTestPoly) ... ok
testVerticesUnsafe (test_shape.UnitTestPoly) ... ok
testBB (test_shape.UnitTestSegment) ... ok
testPickle (test_shape.UnitTestSegment) ... ok
testProperties (test_shape.UnitTestSegment) ... ok
testPropertiesUnsafe (test_shape.UnitTestSegment) ... ok
testSegmentSegmentCollision (test_shape.UnitTestSegment) ... ok
testSetNeighbors (test_shape.UnitTestSegment) ... ok
testArea (test_shape.UnitTestShape) ... ok
testCenterOfGravity (test_shape.UnitTestShape) ... ok
testCollisionType (test_shape.UnitTestShape) ... ok
testDensity (test_shape.UnitTestShape) ... ok
testElasticity (test_shape.UnitTestShape) ... ok
testFilter (test_shape.UnitTestShape) ... ok
testFriction (test_shape.UnitTestShape) ... ok
testMass (test_shape.UnitTestShape) ... ok
testMoment (test_shape.UnitTestShape) ... ok
testNoBody (test_shape.UnitTestShape) ... ok
testPickle (test_shape.UnitTestShape) ... ok
testPointQuery (test_shape.UnitTestShape) ... ok
testRemoveBody (test_shape.UnitTestShape) ... ok
testSegmentQuery (test_shape.UnitTestShape) ... ok
testSensor (test_shape.UnitTestShape) ... ok
testShapesCollide (test_shape.UnitTestShape) ... ok
testSpace (test_shape.UnitTestShape) ... ok
testSurfaceVelocity (test_shape.UnitTestShape) ... ok
testSwitchBody (test_shape.UnitTestShape) ... ok
testConstants (test_shape_filter.UnitTestShapeFilter) ... ok
testEq (test_shape_filter.UnitTestShapeFilter) ... ok
testInit (test_shape_filter.UnitTestShapeFilter) ... ok
testPickle (test_shape_filter.UnitTestShapeFilter) ... ok
testAddRemove (test_space.UnitTestSpace) ... ok
testAddRemoveInStep (test_space.UnitTestSpace) ... ok
testBBQuery (test_space.UnitTestSpace) ... ok
testBBQuerySensor (test_space.UnitTestSpace) ... ok
testCollisionHandlerBegin (test_space.UnitTestSpace) ... ok
testCollisionHandlerBeginNoReturn (test_space.UnitTestSpace) ... ok
testCollisionHandlerPostSolve (test_space.UnitTestSpace) ... ok
testCollisionHandlerPreSolve (test_space.UnitTestSpace) ... ok
testCollisionHandlerPreSolveNoReturn (test_space.UnitTestSpace) ... ok
testCollisionHandlerSeparate (test_space.UnitTestSpace) ... ok
testCopyMethods (test_space.UnitTestSpace) ... ok
testDebugDraw (test_space.UnitTestSpace) ... ok
testDefaultCollisionHandler (test_space.UnitTestSpace) ... ok
testPointQuery (test_space.UnitTestSpace) ... ok
testPointQueryNearest (test_space.UnitTestSpace) ... ok
testPointQueryNearestSensor (test_space.UnitTestSpace) ... ok
testPointQueryNearestWithShapeFilter (test_space.UnitTestSpace) ... ok
testPointQuerySensor (test_space.UnitTestSpace) ... ok
testPostStepCallback (test_space.UnitTestSpace) ... ok
testProperties (test_space.UnitTestSpace) ... ok
testReindexShape (test_space.UnitTestSpace) ... ok
testReindexShapesForBody (test_space.UnitTestSpace) ... ok
testReindexStatic (test_space.UnitTestSpace) ... ok
testReindexStaticCollision (test_space.UnitTestSpace) ... ok
testRemoveInStep (test_space.UnitTestSpace) ... ok
testSegmentQuery (test_space.UnitTestSpace) ... ok
testSegmentQueryFirst (test_space.UnitTestSpace) ... ok
testSegmentQueryFirstSensor (test_space.UnitTestSpace) ... ok
testSegmentQuerySensor (test_space.UnitTestSpace) ... ok
testShapeQuery (test_space.UnitTestSpace) ... ok
testShapeQuerySensor (test_space.UnitTestSpace) ... ok
testStaticPointQueries (test_space.UnitTestSpace) ... ok
testStaticSegmentQueries (test_space.UnitTestSpace) ... ok
testThreaded (test_space.UnitTestSpace) ... ok
testWildcardCollisionHandler (test_space.UnitTestSpace) ... ok
testIdentity (test_transform.UnitTestTransform) ... ok
testInit (test_transform.UnitTestTransform) ... ok
testPickle (test_transform.UnitTestTransform) ... ok
testAnglesDegrees (test_vec2d.UnitTestVec2d) ... ok
testAnglesRadians (test_vec2d.UnitTestVec2d) ... ok
testComparison (test_vec2d.UnitTestVec2d) ... ok
testCreationAndAccess (test_vec2d.UnitTestVec2d) ... ok
testCross (test_vec2d.UnitTestVec2d) ... ok
testHighLevel (test_vec2d.UnitTestVec2d) ... ok
testInplace (test_vec2d.UnitTestVec2d) ... ok
testLength (test_vec2d.UnitTestVec2d) ... ok
testMath (test_vec2d.UnitTestVec2d) ... ok
testPickle (test_vec2d.UnitTestVec2d) ... ok
testReverseMath (test_vec2d.UnitTestVec2d) ... ok
testUnary (test_vec2d.UnitTestVec2d) ... ok

----------------------------------------------------------------------
Ran 182 tests in 0.346s

OK
```

What is this one testing and why does it fail only sometimes?

**Comment by viblo** [comment]
It happens for me as well, both in python 2.7 and 3.4. I dont remember the exact thing that test it supposed to test, but I think its just a coincidence that it fails. It seems like `testAddRemoveInStep` is the real test that fails.

**Comment by viblo** [comment]
This is the stack trace when I ctrl-c:
```testAddRemoveInStep (tests.test_space.UnitTestSpace) ... Traceback (most recent call last):
  File "run_tests.py", line 31, in <module>
    unittest.TextTestRunner(verbosity=2).run(x)
  File "C:\Python27\lib\unittest\runner.py", line 151, in run
    test(result)
  File "C:\Python27\lib\unittest\case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "..\tests\test_space.py", line 151, in testAddRemoveInStep
    s.step(.1)
  File "..\pymunk\space.py", line 410, in step
    self.add(objs)
  File "..\pymunk\space.py", line 261, in add
    self._add_later.put(objs)
  File "C:\Python27\lib\Queue.py", line 138, in put
    self.not_empty.notify()
  File "C:\Python27\lib\threading.py", line 389, in notify
    self._note("%s.notify(): no waiters", self)
KeyboardInterrupt```

**Comment by Berserker66** [comment]
Abandoned the thread idea. It is certainly possible, but to do it properly would require backward-compatibility breaking changes, which I'll just assume is not going to get accepted.

**Comment by Berserker66** [comment]
The latest change uses small functions to call the add and remove loops, due to less asking of are we in a loop this version runs up to 3 times as fast through the tests as the current pymunk does.

This is just a raw benefit, no threading. Just something I saw when using a profiler.
There are still 2 tests failing and I'm not sure why. I might also just be too tired to find out (4 AM, time to sleep)

**Comment by Berserker66** [comment]
Need some feedback for the last failing test.

In the test testAddRemoveInStep, the pre_solve_remove tries to remove the b and c bodies 3 times, due to triggering during 3 solves.
Before, this worked, because they got added to a set, so multiple removes were ignored.

Should this behavior be preserved, or is it a bug in the first place?

**Comment by Berserker66** [comment]
Some background info on the test:

```
    def testAddRemoveInStep(self):
        s = p.Space()

        b1 = p.Body(1, 2)
        c1 = p.Circle(b1, 2)

        b2 = p.Body(1, 2)
        c2 = p.Circle(b2, 2)

        s.add(b1, b2, c1, c2)

        b = p.Body(1, 2)
        c = p.Circle(b, 2)
        
        def pre_solve_add(arbiter, space, data):
            space.add(b, c)
            self.assertTrue(b not in s.bodies)
            self.assertTrue(c not in s.shapes)
            return True

        def pre_solve_remove(arbiter, space, data):
            print("Trying to run pre_solve remove")
            space.remove(b, c)
            self.assertTrue(b in s.bodies)
            self.assertTrue(c in s.shapes)
            print("Ending pre solve")
            return True

        s.add_collision_handler(0, 0).pre_solve = pre_solve_add

        s.step(.1)
        
        self.assertTrue(b in s.bodies)
        self.assertTrue(c in s.shapes)

        s.add_collision_handler(0, 0).pre_solve = pre_solve_remove
        print("Starting Step")
        s.step(.1)
        print("Checking result")
        self.assertTrue(b not in s.bodies)
        self.assertTrue(c not in s.shapes)
```

Prints:

```
Starting Step
Trying to run pre_solve remove
Ending pre solve
Trying to run pre_solve remove
Ending pre solve
Trying to run pre_solve remove
Ending pre solve
```

**Comment by viblo** [comment]
I think the reasoning behind is that if you have a callback to remove items that touch the ground or a wall you can trigger multiple removes in the step. There is no easy way for the user to check if its already removed from the callback except wrapping it in a try/except, and the error itself might only happen very seldom (depending on the shapes in the space), so omitting try/except wont be seen directly. By allowing multiple removes a tricky to find bug is avoided in a easy way.

**Comment by Berserker66** [comment]
The thing is, depending on how you packed it, it could have failed anyway.

Say you have space.remove(a,b) and later space.remove(a), then it also would have tried to remove a twice and you would have crashed. Due to (a,b) and a being two different entries in the dict.

So, yeah, as long as you don't wrap into a tuple or other container, your reasoning holds true, but it falls apart in the current version if you use containers.

Additionally, what about adding items? Should that also be limited to uniques?

Just wanting to figure out and confirm what the expected result is, so I can implement that.

**Comment by Berserker66** [comment]
So, I've made the last commit under the assumption to make the behavior consistent across all operations.

ANY duplicate remove or add is now ignored, not just under certain circumstances.

Speed is still slightly better. Tests pass in 275 ms vs 333ms before (this is only the inner time spent in the tests). and of course, it is a lot more rigid against threading. If I found all threading issues remains to be seen, but it is certainly better.

**Comment by viblo** [comment]
Ah, the fact that but space.remove(a) was safe but not space.remove(a,b) looks like a bug. You are of course right that they should behave the same.

**Comment by viblo** [comment]
I was thinking about the thread safety a bit. To make all of Pymunk safe would mean that all calls to chipmunk (more or less) needs to be wrapped in a space-global lock? Or does CFFI guarantee that the C code is never called from more than one thread at a time?

Lets say for example that I update the sleeping property on a body. That will manipulate a lot of things inside Chipmunk (and I dont think Chipmunk is generally thread safe). So to protect it we need a space-global lock. Even doing very basic things as setting the gravity on the space will do things that doesnt seem safe.

**Comment by Berserker66** [comment]
Generally it should be mostly safe - sometimes you might get slightly random results, due to random order of events, which is something client code needs to figure out, as even with locks there is still no guarantee which lock is acquired first.

Writing to the same data structures from multiple sources is actually safe, if you read and write you might get transient values, which depending on the situation might be acceptable - or not.

In the end, the best way would be to write up some tests and see. I was just going to leave it for now and see if I find another issue as I carry on with my project, which has a lot of threads. And continue to pull-request improve on it as it happens.

As for cffi being thread safe, if you google for it you can see them working on it and a few closed issues that have been resolved. So, it tries to be.


Bottomline -
This pull request should only improve things, I don't see any regressions, as such I'd like to request it be merged. Should there be more to be added, I can make a new PR for it.

Extra; a little clip from my still very early project, using chromium for the UI, vulkan for rendering and now pymunk for physics. (I don't have an entity renderer yet, so you don't see the bouncy ball, you need to imagine for now)
https://i.imgur.com/256nKoR.gifv

**Comment by viblo** [comment]
There can be more serious problems. For example, one thread removing a sleeping body and one thread setting gravity would make the code segfault (or worse) since setting gravity will loop through the sleeping bodies of the space. Im sure there are a lots of similar cases.

I assumed CFFI is thread safe in my previous comment (that was obviously bad, should have checked it). But my point was that if CFFI does not guards so only one thread can call out to c code at a time there will be thread safety issues in Chipmunk similar to the gravity/remove example above. 

I didnt consider the safety of Chipmunk until my comment yesterday. Now when I think of it Im a bit hesitant since it could give the impression that pymunk is thread safe when its not, and there might be other hidden issues I will leave the PR here a bit to have time to evaluate properly.

(Cool to see your project, from your requirements and discussions here it sounds like it will be quite advanced. Already looks promising, I hope you make updates when you have more progress!)

**Comment by Berserker66** [comment]
Well, I wouldn't recommend to advertise thread safety, especially if you know there are issues, this just improves the situation a bit.

What I meant with most thread locks will have to happen in client code anyway, is for example this piece of code:

```
        with simulation.lock:
            simulation.space.remove(self.body)
            simulation.space.remove(self.shapes)
            body = self.body = Body()
            
            for segment in vec.v:
                shapes.add(pymunkSegment(body, (segment.x1, segment.y1), (segment.x2, segment.y2), 3))

            simulation.space.add(self.body)
            simulation.space.add(shapes)
```

Now, this will always need to be thread-locked by client code, this is triggered when a chunk has to be changed, due to tiles being removed or added. For now, there is no incremental change (and there may never be, since removing and re-adding is rather quick), so I'm removing the chunk wholesome and then re-adding it.

Even if Pymunk had locks on every space function call to protect itself against segfaults (which is still a reasonable thing to do), this code would still sometimes remove the chunk, then another thread would call step and then the rest is added, resulting in something moving into the chunk. This kind of logic error always needs to be protected from a client lock, and in my multi-threaded project I have a few of those, including for modules that are thread-safe, you just can't escape it.
I'm not saying, to not use thread locks. They most certainly can be added. Just pointing out that it may be worthwhile to let the programmer know of the threading pitfalls and let them handle it. Those that attempt multi-threading usually know that extra work is involved.

**Comment by Berserker66** [comment]
Thinking some more of it, and also looking at various other physics engines - 
The more modern 3D engines do allow multi-threading of just about everything, but before that we had the typical "physics-thread", doing most of the work. However, what most engines still did, such as Unreal Engine 3, is to create and destroy objects on other threads.

So, typical setup was a physics thread that was handling all physics tasks, with other threads adding and removing objects, and some other tangential work. This kind of architecture should be supported, I think.

**Comment by Berserker66** [comment]
So, something I don't really know how to debug. During closing of my program, occasionally I get a python has stopped working message.

If I tell Visual Studio to debug it, this is what I get:
https://i.imgur.com/Jd1VxsD.png

This also occurs on the current public version from pypi, though with the small change to prevent duplicate shape IDs.
Any idea on how this can be fixed? Any other debugging method I should try to get more info?

**Comment by viblo** [comment]
I have seen this as well, but havent looked closed. Previously it was fixed with adding weakref and ensuring the order of GC. When I had similar issue in a previous version of pymunk I think I enabled debug symbols in chipmunk (so that I could see the which (type of) object that doesnt exist anymore), and also adding print statements on __del__ to see the order of GC. But it was still difficult to find.

**Comment by Berserker66** [comment]
The thing is, that this happens after the threads are long gone. I have an explicit shutdown order;
```
DEBUG:root:Shutting down
DEBUG:root:Mainloop stopped.
DEBUG:root:Threadsystem Exit
DEBUG:root:Signalled CEF Shutdown
DEBUG:root: - Main Thread Exit - 

Process finished with exit code -1073741819 (0xC0000005)
```
The Threadsystem contains all the threads that deal with chunks/worlds and they get joined. Later I shutdown Chromium embedded framework, which has its own thread and subprocess. Then when everything is joined I exit the main thread and let the rest GC. And that is when it happens.

**Comment by viblo** [comment]
Closing this PR since its too old. If there's new work related to threading its better to open a new PR or issue. (But no guarantees around merging, will need discussion and thoughts just like happened here)

**Pull request closed without merging**
